### ISSUE TITLE
Absence of "unsigned long long" type constructor for BigInt or strange testing manner

### ISSUE THREAD

**Issue by pravog** [QuasarApp/mini-gmp#1]
In tests there is code like 
```
void arithmetictests::binaryArithmeticDivModTest() {
    BigInt num1 = static_cast<unsigned long long>(313233343536373839);
```
but there is no constructor for this type ... only these constructors
``` BigInt();    
    BigInt(const BigInt& val, int bitCount = -1);
    BigInt(const std::string &imput, int base = 10);
    BigInt(long val);
    BigInt(char item, unsigned int size, int base);
```
so most likely BigInt(long val); will be used and as a result the "big-number-constant" will be truncated during convertion to long for target processors with sizeof(long) < sizeof(unsigned long long) ... 32-bit processors for sure.
I think there is a need in "unsigned long long" BigInt constructor if testing is done with this type. Or tests should be rewritten to "long" type.
Is there any sense to keep long-constructor available (and just add "unsigned long long" constructor) ... for faster constructing from "small" constants on 32bits targets?
P.S.
Please run tests for 32bit machines also (at least before releases) :)

**Comment by EndrII** [comment]
Thanks for your feedback. This bug we'll be fixed in next release.
